server:
  port: 9290
  servlet:
    context-path: /discoveryservice
  ssl:
    enabled: true
    client-auth: want
    key-store: file:c:\tmp\ssl\ssltest.p12
    key-store-password: Tba,77to
    key-store-type: PKCS12
  #    key-alias: ssltest


eureka:
  instance:
    hostname: localhost
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-virtual-host-name: ${spring.application.name}
#    home-page-url-path: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/
    home-page-url: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/
#    status-page-url-path: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/info
    status-page-url: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/health
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: https://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
#    metadata-map:
#      hostname : ${eureka.instance.hostname}
#      securePort: ${server.port}


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF